version: '3'

services:
  mysql:
    image: mysql:5.7.28
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_INITDB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWD}
    ports:
      - ${MYSQL_PORT}:3306
      - 33060:33060
    volumes:
      - ${MYSQL_DIR}/mysql:/var/lib/mysql
    stdin_open: true
    tty: true